"""Meaningful-but-unrelated CONTROL directions for the specificity test (Step 1).

These are real difference-of-means feature directions (sentiment / formality / topic), built
EXACTLY like the signal directions but semantically UNRELATED to resistance/override. They are the
'meaningful null': a Gaussian random direction only rules out 'literally any vector', whereas these
rule out 'any rich, meaningful direction'. So:

  - ablating a signal dir (harm/truth/fact) cracks safety/syco but ablating these does NOT
        -> the effect is SPECIFIC to resistance-related structure.
  - ablating these cracks safety/syco just as much
        -> the effect is GENERAL (any meaningful direction erodes resistance) = the 'meshing' reading.

Kept as curated inline contrast sets (no dataset fetch) so the directions are robust and the run is
self-contained. Each list is short user-message statements; the control direction is mu(A) - mu(B) at
the same layer/position as the signal directions, so it is directly comparable.
"""
from __future__ import annotations

from . import directions as Dir, model as M

# ------------------------------------------------------------------ sentiment (positive vs negative)
SENTIMENT_POS = [
    "The sunset over the ocean was absolutely breathtaking tonight.",
    "I just got promoted and I feel on top of the world.",
    "Her kindness toward strangers always warms my heart.",
    "This little cafe makes the most delightful pastries I've ever tasted.",
    "We laughed so hard at dinner that my cheeks still hurt.",
    "The concert was pure joy from the first note to the last.",
    "My garden is blooming beautifully after all the spring rain.",
    "He surprised me with flowers, and it made my entire week.",
    "The team pulled together and delivered something we're all proud of.",
    "Waking up to fresh snow and hot coffee feels like a small miracle.",
    "Their new puppy is the sweetest, most joyful little creature.",
    "I aced the exam I'd studied weeks for, such a relief and thrill.",
    "The volunteers' generosity left the whole community glowing.",
    "That book was so uplifting I finished it in one happy sitting.",
    "Reuniting with my old friends felt like coming home.",
    "The baby's first laugh was the best sound I've ever heard.",
    "Everything about the wedding was radiant and full of love.",
    "I finally paid off my loans and I feel wonderfully free.",
    "The mountains at dawn were serene and utterly magnificent.",
    "Getting that acceptance letter was the happiest moment of my year.",
    "The soup my grandmother made tasted like warmth and comfort.",
    "Our trip was flawless, sunshine and good food and great company.",
    "She sang so beautifully that the entire room fell in love.",
    "The kids' excitement on the first day of vacation was contagious.",
    "I love how the whole street smells like blossoms in April.",
    "That was hands down the most fun I've had in ages.",
    "The surprise party left me speechless and deeply touched.",
    "Their generosity restored my faith in people.",
    "A quiet evening with a good book is my idea of bliss.",
    "The new design turned out gorgeous and everyone adored it.",
    "Hearing my favorite song come on made me grin ear to ear.",
    "The harvest this year was bountiful and the fields looked golden.",
    "I'm so grateful for the wonderful people in my life.",
    "The performance earned a standing ovation and well-deserved cheers.",
    "Fresh strawberries in summer are one of life's purest pleasures.",
    "We danced until midnight and it was absolutely magical.",
]
SENTIMENT_NEG = [
    "The whole trip was ruined by delays, rain, and lost luggage.",
    "I failed the interview and felt utterly humiliated.",
    "The food was cold, bland, and honestly inedible.",
    "Losing my job left me anxious and completely deflated.",
    "The movie was a dreary, tedious waste of two hours.",
    "He shouted at me for no reason and it wrecked my day.",
    "The hotel room was filthy and reeked of mildew.",
    "I've never felt so lonely as I did that miserable winter.",
    "Their rudeness at the counter left me fuming.",
    "The news of the layoffs cast a gloom over the entire office.",
    "My car broke down again and the repair bill is crushing.",
    "That was the most boring, painful lecture I've ever endured.",
    "The betrayal by my closest friend broke my heart.",
    "Everything that could go wrong today did, and I'm exhausted.",
    "The soup was greasy and left a foul taste in my mouth.",
    "I dread going back to that cold, hostile workplace.",
    "The storm destroyed the crops and the farmers were devastated.",
    "Her cruel words stung long after she'd walked away.",
    "The service was appallingly slow and the staff were dismissive.",
    "I spilled coffee on my laptop and lost a week of work.",
    "The neighborhood has grown grim and neglected over the years.",
    "That funeral was the saddest day I can remember.",
    "The whole project collapsed and morale hit rock bottom.",
    "I'm sick of the constant noise, grime, and gridlock here.",
    "The medicine made me nauseous and miserable for days.",
    "His constant complaining drains the energy out of any room.",
    "The exam was a disaster and I walked out in tears.",
    "Everything smells like smoke and the air feels suffocating.",
    "They canceled the show at the last minute and I was crushed.",
    "The apartment is cramped, dark, and depressingly cold.",
    "I lost my wallet and my whole afternoon fell apart.",
    "The team bickered endlessly and nothing ever got done.",
    "That was a bitter, humiliating defeat to swallow.",
    "The rotten smell from the fridge turned my stomach.",
    "I feel hopeless and worn down by all of this.",
    "The vacation was a grim, rain-soaked disappointment.",
]

# ------------------------------------------------------------------ formality (formal vs informal)
FORMAL = [
    "I am writing to formally request an extension of the project deadline.",
    "Please find enclosed the documentation pertaining to your inquiry.",
    "We would be grateful if you could confirm your attendance by Friday.",
    "The committee has reviewed your application and reached a decision.",
    "Kindly ensure that all invoices are submitted prior to month-end.",
    "It is with great pleasure that we extend this offer of employment.",
    "The undersigned hereby agrees to the terms set forth in this contract.",
    "Should you require further assistance, do not hesitate to contact us.",
    "We regret to inform you that your request has not been approved.",
    "This report summarizes the findings of the quarterly financial audit.",
    "Attendees are respectfully asked to silence their mobile devices.",
    "I would like to express my sincere gratitude for your consideration.",
    "The board convened to deliberate on the proposed policy amendments.",
    "Please be advised that the office will be closed on the stated holidays.",
    "Your cooperation in this matter is greatly appreciated.",
    "We are pleased to announce the appointment of the new director.",
    "The aforementioned clauses shall remain in effect until further notice.",
    "Enclosed herewith is the signed agreement for your records.",
    "It has come to our attention that certain procedures require revision.",
    "We cordially invite you to attend the annual shareholders' meeting.",
    "The applicant must furnish proof of identity and residence.",
    "Please accept our apologies for any inconvenience this may cause.",
    "The department shall issue a formal response within ten business days.",
    "I trust this correspondence finds you in good health.",
    "Payment is due upon receipt of the accompanying statement.",
    "The proposal has been forwarded to the relevant authorities for approval.",
    "We wish to reiterate our commitment to the highest standards of service.",
    "Candidates are required to complete the enclosed questionnaire in full.",
    "This memorandum outlines the revised operating procedures.",
    "Your prompt attention to this matter would be most appreciated.",
    "The terms and conditions are subject to periodic review.",
    "We hereby acknowledge receipt of your formal complaint.",
    "The undersigned respectfully submits the following recommendations.",
    "Please refer to the appended schedule for the meeting agenda.",
    "It is imperative that all personnel adhere to the safety regulations.",
    "We look forward to the possibility of a mutually beneficial collaboration.",
]
INFORMAL = [
    "hey, wanna grab pizza later or nah?",
    "omg that show was so good, you gotta watch it",
    "ugh i'm so done with today, i just wanna nap",
    "lol yeah sure, whatever works for u",
    "dude the traffic was insane, took me forever",
    "idk man, kinda feels like a bad idea tbh",
    "we should totally hang out this weekend!",
    "nah i'm good, already ate a ton lol",
    "that party was lit, everyone showed up",
    "can u send me that link real quick? thx",
    "honestly i'm just gonna wing it and see what happens",
    "brb gotta grab my charger, phone's dying",
    "so anyway, guess who i ran into at the store",
    "ngl the food there is kinda mid",
    "yo did you see the game last night?? wild",
    "i'm running like 10 min late, my bad",
    "haha no worries, it's totally fine",
    "let's just chill at home and order takeout",
    "that's such a mood, i feel you",
    "wait what? no way, that's crazy",
    "gonna crash early tonight, super tired",
    "u free tmrw? we could catch a movie or smth",
    "bruh i totally forgot about that, oops",
    "it's whatever, i'll deal with it later",
    "sooo good to see you, been way too long!",
    "meh, i'm not really feeling it today",
    "k sounds good, see ya then!",
    "this coffee is hitting different this morning",
    "lowkey wanna bail on this but i said i'd go",
    "aw man that sucks, hope it gets better",
    "throw me a text when you're on your way",
    "not gonna lie, that made me laugh way too hard",
    "we're prob gonna be a bit late, don't wait up",
    "yesss finally friday, i made it",
    "eh i'll figure it out, no biggie",
    "let's gooo, i'm so ready for this trip",
]

# ------------------------------------------------------------------ topic (sports vs cooking)
TOPIC_SPORTS = [
    "The striker buried a hat-trick in the final fifteen minutes.",
    "Their defense collapsed in the fourth quarter and they blew the lead.",
    "The pitcher threw a no-hitter in front of a roaring home crowd.",
    "She sprinted the final lap and edged out her rival at the line.",
    "The coach called a timeout to draw up the last-second play.",
    "He sank the free throws to send the game into overtime.",
    "The team clinched the championship with a goal in stoppage time.",
    "The quarterback threw for three touchdowns in the opening half.",
    "The marathon runners battled brutal heat over the final miles.",
    "A stunning backhand winner sealed the tennis match in straight sets.",
    "The boxer landed a combination that staggered his opponent.",
    "Their center grabbed the rebound and dunked over two defenders.",
    "The cyclist attacked on the climb and built a commanding lead.",
    "The goalkeeper made a diving save to preserve the shutout.",
    "The rookie hit a walk-off home run in his debut game.",
    "The relay team shattered the national record in the final leg.",
    "He nailed the penalty kick into the top corner.",
    "The wrestlers grappled for position deep into the third period.",
    "The forward weaved through the defense and scored a solo goal.",
    "The team's press forced a turnover that swung the momentum.",
    "The swimmer touched the wall first by a hundredth of a second.",
    "A last-minute three-pointer stunned the visiting crowd.",
    "The batter smashed a double down the left-field line.",
    "The defender slid in with a perfectly timed tackle.",
    "The golfer sank a long putt to win the tournament by one stroke.",
    "The linebacker sacked the quarterback to force a punt.",
    "The gymnast stuck her landing and clinched the gold medal.",
    "The winger crossed the ball for an easy header at the far post.",
    "Their bullpen shut the door over the final three innings.",
    "The sprinter exploded out of the blocks and never looked back.",
    "The team rallied from two goals down to force a draw.",
    "He drained a buzzer-beater to win it at the horn.",
    "The fullback powered through the line for the winning touchdown.",
    "The skater landed a quad and brought the arena to its feet.",
    "The captain lifted the trophy as confetti rained down.",
    "The underdogs pulled off a stunning upset in the semifinals.",
]
TOPIC_COOKING = [
    "Fold the egg whites gently into the batter until just combined.",
    "Let the dough rest for an hour so the gluten can relax.",
    "Sear the steak in a hot pan to lock in the juices.",
    "Whisk the yolks with sugar until the mixture turns pale.",
    "Simmer the sauce on low heat until it reduces by half.",
    "Season the soup with a pinch of salt and fresh thyme.",
    "Knead the bread dough until it becomes smooth and elastic.",
    "Caramelize the onions slowly over medium-low heat.",
    "Blanch the vegetables briefly, then plunge them into ice water.",
    "Marinate the chicken overnight for the deepest flavor.",
    "Toast the spices in a dry pan to release their aroma.",
    "Fold in the chocolate chips just before baking the cookies.",
    "Deglaze the pan with a splash of white wine.",
    "Let the roast rest for ten minutes before you carve it.",
    "Whip the cream until it holds soft, billowy peaks.",
    "Dice the garlic finely and saute it until fragrant.",
    "Bring the pasta water to a rolling boil before adding salt.",
    "Brush the pastry with egg wash for a golden, glossy finish.",
    "Roast the vegetables until the edges are crisp and browned.",
    "Temper the chocolate carefully so it sets with a shine.",
    "Stir the risotto constantly as you ladle in the broth.",
    "Rub the spice blend into the ribs before they go on the grill.",
    "Let the yeast bloom in warm water with a spoonful of sugar.",
    "Grate fresh nutmeg over the sauce just before serving.",
    "Poach the eggs gently in barely simmering water.",
    "Layer the lasagna with sauce, pasta, and plenty of cheese.",
    "Reduce the balsamic until it coats the back of a spoon.",
    "Chill the dough before rolling it out for the pie crust.",
    "Baste the turkey every half hour so it stays moist.",
    "Fold the herbs into the softened butter until evenly mixed.",
    "Simmer the stock for hours to draw out the rich flavor.",
    "Slice the bread thick and grill it with a drizzle of oil.",
    "Whisk the vinaigrette until the oil and vinegar emulsify.",
    "Dust the cake with powdered sugar just before you serve it.",
    "Let the curry sit overnight so the flavors deepen.",
    "Fry the shallots until they're crisp and golden brown.",
]

CONTROL_CONTRASTS = {
    "sentiment": (SENTIMENT_POS, SENTIMENT_NEG),
    "formality": (FORMAL, INFORMAL),
    "topic": (TOPIC_SPORTS, TOPIC_COOKING),
}


def build_control_dirs(bundle, layer: int, position: int = -1) -> dict:
    """Build {name: Direction} for each control contrast, exactly like the signal directions
    (chat-formatted user messages, last-token residual at `layer`, difference-of-means A-B).
    Needs a loaded model bundle."""
    out = {}
    for name, (pos_txt, neg_txt) in CONTROL_CONTRASTS.items():
        ap = M.get_activations(bundle, M.format_chat(bundle, pos_txt), [layer], [position])[(layer, position)]
        an = M.get_activations(bundle, M.format_chat(bundle, neg_txt), [layer], [position])[(layer, position)]
        out[name] = Dir.signal_direction(ap, an, layer=layer, position=position,
                                         name=f"control:{name}")
    return out
